Repository blubincod/petmily, pull requests merged in 2024-08, with the labels that each got.

#3 pet develop-set
  src/main/java/com/concord/petmily/pet/controller/PetController.java
  src/main/java/com/concord/petmily/pet/entity/Pet.java
  src/main/java/com/concord/petmily/pet/repository/PetRepository.java
  src/main/java/com/concord/petmily/pet/service/PetService.java
Labels: documentation

#6 게시판 Entity, controller 뼈대 작성
  src/main/java/com/concord/petmily/post/controller/PostController.java
  src/main/java/com/concord/petmily/post/dto/PostDto.java
  src/main/java/com/concord/petmily/post/dto/PostRequestDTO.java
  src/main/java/com/concord/petmily/post/dto/PostResponseDTO.java
  src/main/java/com/concord/petmily/post/entity/Post.java
  src/main/java/com/concord/petmily/post/entity/PostCategory.java
  src/main/java/com/concord/petmily/post/entity/PostStatus.java
  src/main/java/com/concord/petmily/post/service/PostService.java
Labels: Feature

#7 웹에서 현재 위치 정보를 서버로 전송하는 기능 추가
  build.gradle
  src/main/java/com/concord/petmily/common/controller/PageController.java
  src/main/java/com/concord/petmily/walk/controller/WalkController.java
  src/main/java/com/concord/petmily/walk/dto/WalkDto.java
  src/main/java/com/concord/petmily/walk/dto/WalkLocationDto.java
  src/main/java/com/concord/petmily/walk/entity/Walk.java
  src/main/java/com/concord/petmily/walk/repository/WalkRepository.java
  src/main/java/com/concord/petmily/walk/service/WalkService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/walk.html
Labels: Feature

#9 사용자 및 인증 모듈 초기 설정
  .gitattributes
  build.gradle
  src/main/java/com/concord/petmily/auth/controller/AuthController.java
  src/main/java/com/concord/petmily/auth/controller/TokenApiController.java
  src/main/java/com/concord/petmily/auth/dto/CreateAccessTokenRequest.java
  src/main/java/com/concord/petmily/auth/dto/CreateAccessTokenResponse.java
  src/main/java/com/concord/petmily/auth/dto/JwtAuthenticationResponse.java
  src/main/java/com/concord/petmily/auth/dto/JwtProperties.java
  src/main/java/com/concord/petmily/auth/dto/LoginRequest.java
  src/main/java/com/concord/petmily/auth/entity/RefreshToken.java
  src/main/java/com/concord/petmily/auth/repository/RefreshTokenRepository.java
  src/main/java/com/concord/petmily/auth/security/TokenAuthenticationFilter.java
  src/main/java/com/concord/petmily/auth/security/WebSecurityConfig.java
  src/main/java/com/concord/petmily/auth/service/RefreshTokenService.java
  src/main/java/com/concord/petmily/auth/service/TokenProvider.java
  src/main/java/com/concord/petmily/auth/service/TokenService.java
  src/main/java/com/concord/petmily/post/service/PostService.java
  src/main/java/com/concord/petmily/user/controller/UserController.java
  src/main/java/com/concord/petmily/user/dto/AddUserRequest.java
  src/main/java/com/concord/petmily/user/entity/User.java
  src/main/java/com/concord/petmily/user/exception/CustomExceptions.java
  src/main/java/com/concord/petmily/user/repository/UserRepository.java
  src/main/java/com/concord/petmily/user/service/UserDetailService.java
  src/main/java/com/concord/petmily/user/service/UserService.java
  src/main/resources/application.yml
  src/test/http/user.http
Labels: Feature

#14 게시판 CRUD, 댓글 기능 구현
  src/main/java/com/concord/petmily/PetmilyApplication.java
  src/main/java/com/concord/petmily/comment/controller/CommentController.java
  src/main/java/com/concord/petmily/comment/dto/CommentDto.java
  src/main/java/com/concord/petmily/comment/entity/Comment.java
  src/main/java/com/concord/petmily/comment/repository/CommentRepository.java
  src/main/java/com/concord/petmily/comment/service/CommentService.java
  src/main/java/com/concord/petmily/post/controller/PostController.java
  src/main/java/com/concord/petmily/post/dto/PostDto.java
  src/main/java/com/concord/petmily/post/dto/PostRequestDTO.java
  src/main/java/com/concord/petmily/post/dto/PostResponseDTO.java
  src/main/java/com/concord/petmily/post/entity/BaseTimeEntity.java
  src/main/java/com/concord/petmily/post/entity/Post.java
  src/main/java/com/concord/petmily/post/entity/PostCategory.java
  src/main/java/com/concord/petmily/post/repository/PostCategoryRepository.java
  src/main/java/com/concord/petmily/post/repository/PostRepository.java
  src/main/java/com/concord/petmily/post/service/PostService.java
  src/main/resources/import.sql
  src/test/http/post.http
Labels: Feature

#13 전역 예외 처리 기능 추가
  src/main/java/com/concord/petmily/auth/controller/AuthController.java
  src/main/java/com/concord/petmily/auth/entity/RefreshToken.java
  src/main/java/com/concord/petmily/auth/exception/AuthException.java
  src/main/java/com/concord/petmily/auth/security/TokenAuthenticationFilter.java
  src/main/java/com/concord/petmily/auth/service/RefreshTokenService.java
  src/main/java/com/concord/petmily/auth/service/TokenProvider.java
  src/main/java/com/concord/petmily/auth/service/TokenService.java
  src/main/java/com/concord/petmily/common/exception/ErrorCode.java
  src/main/java/com/concord/petmily/common/exception/ErrorResponse.java
  src/main/java/com/concord/petmily/common/exception/GlobalExceptionHandler.java
  src/main/java/com/concord/petmily/user/controller/UserController.java
  src/main/java/com/concord/petmily/user/entity/User.java
  src/main/java/com/concord/petmily/user/exception/CustomExceptions.java
  src/main/java/com/concord/petmily/user/exception/UserException.java
  src/main/java/com/concord/petmily/user/exception/UserNotFoundException.java
  src/main/java/com/concord/petmily/user/service/UserService.java
  src/test/http/user.http
Labels: Feature, WIP

#17 CSRF 문제로 인한 POST 요청의 403 오류 수정 (#16)
  src/main/java/com/concord/petmily/auth/security/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/http/user.http
Labels: Bugfix

#19 Post 좋아요, 조회수 구현
  src/main/java/com/concord/petmily/comment/controller/CommentController.java
  src/main/java/com/concord/petmily/comment/exception/CommentException.java
  src/main/java/com/concord/petmily/comment/service/CommentService.java
  src/main/java/com/concord/petmily/common/exception/ErrorCode.java
  src/main/java/com/concord/petmily/common/exception/GlobalExceptionHandler.java
  src/main/java/com/concord/petmily/likes/controller/LikesController.java
  src/main/java/com/concord/petmily/likes/dto/LikesDto.java
  src/main/java/com/concord/petmily/likes/entity/Likes.java
  src/main/java/com/concord/petmily/likes/exception/LikesException.java
  src/main/java/com/concord/petmily/likes/repository/LikesRepository.java
  src/main/java/com/concord/petmily/likes/service/LikesService.java
  src/main/java/com/concord/petmily/post/controller/PostController.java
  src/main/java/com/concord/petmily/post/dto/PostDto.java
  src/main/java/com/concord/petmily/post/entity/Post.java
  src/main/java/com/concord/petmily/post/entity/PostCategory.java
  src/main/java/com/concord/petmily/post/exception/PostException.java
  src/main/java/com/concord/petmily/post/service/PostService.java
  src/main/resources/data.sql
  src/test/http/post.http
Labels: Feature

#20 산책 및 산책 중 활동 기록 기능 추가
  src/main/java/com/concord/petmily/auth/controller/AuthController.java
  src/main/java/com/concord/petmily/auth/dto/JwtProperties.java
  src/main/java/com/concord/petmily/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/concord/petmily/auth/security/SecurityConfig.java
  src/main/java/com/concord/petmily/auth/service/TokenProvider.java
  src/main/java/com/concord/petmily/common/exception/ErrorCode.java
  src/main/java/com/concord/petmily/common/exception/GlobalExceptionHandler.java
  src/main/java/com/concord/petmily/user/controller/UserController.java
  src/main/java/com/concord/petmily/user/entity/Role.java
  src/main/java/com/concord/petmily/user/entity/Status.java
  src/main/java/com/concord/petmily/user/entity/User.java
  src/main/java/com/concord/petmily/user/exception/CustomExceptions.java
  src/main/java/com/concord/petmily/user/service/UserService.java
  src/main/java/com/concord/petmily/walk/controller/WalkController.java
  src/main/java/com/concord/petmily/walk/dto/WalkActivityDto.java
  src/main/java/com/concord/petmily/walk/dto/WalkDto.java
  src/main/java/com/concord/petmily/walk/entity/ActivityType.java
  src/main/java/com/concord/petmily/walk/entity/Walk.java
  src/main/java/com/concord/petmily/walk/entity/WalkActivity.java
  src/main/java/com/concord/petmily/walk/entity/WalkGoal.java
  src/main/java/com/concord/petmily/walk/entity/WalkGroup.java
  src/main/java/com/concord/petmily/walk/entity/WalkGroupId.java
  src/main/java/com/concord/petmily/walk/entity/WalkStatus.java
  src/main/java/com/concord/petmily/walk/exception/WalkAccessDeniedException.java
  src/main/java/com/concord/petmily/walk/exception/WalkException.java
  src/main/java/com/concord/petmily/walk/exception/WalkNotFoundException.java
  src/main/java/com/concord/petmily/walk/repository/WalkActivityRepository.java
  src/main/java/com/concord/petmily/walk/service/WalkService.java
  src/main/resources/application.yml
  src/main/resources/templates/walk.html
  src/test/http/user.http
  src/test/http/walk.http
  src/test/java/com/concord/petmily/walk/WalkControllerTest.java
  src/test/java/com/concord/petmily/walk/WalkServiceTest.java
Labels: Feature

#27 회원의 여러 반려동물 산책 활동 기록 기능 추가 및 WalkActivity 엔티티 관계 변경
  src/main/java/com/concord/petmily/common/exception/GlobalExceptionHandler.java
  src/main/java/com/concord/petmily/common/utils/PasswordHashGenerator.java
  src/main/java/com/concord/petmily/domain/auth/controller/AuthController.java
  src/main/java/com/concord/petmily/domain/auth/security/SecurityConfig.java
  src/main/java/com/concord/petmily/domain/pet/controller/PetController.java
  src/main/java/com/concord/petmily/domain/pet/entity/Category.java
  src/main/java/com/concord/petmily/domain/pet/entity/Gender.java
  src/main/java/com/concord/petmily/domain/pet/entity/Status.java
  src/main/java/com/concord/petmily/domain/pet/service/PetService.java
  src/main/java/com/concord/petmily/domain/pet/service/PetServiceImpl.java
  src/main/java/com/concord/petmily/domain/user/controller/UserController.java
  src/main/java/com/concord/petmily/domain/user/service/UserDetailService.java
  src/main/java/com/concord/petmily/domain/walk/controller/WalkController.java
  src/main/java/com/concord/petmily/domain/walk/dto/StartWalkRequest.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkActivityDto.java
  src/main/java/com/concord/petmily/domain/walk/entity/Walk.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkActivity.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkGroup.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkingPet.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkingPetId.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkRepository.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkingPetRepository.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkService.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkServiceImpl.java
  src/main/resources/data.sql
  src/test/http/pet.http
  src/test/http/user.http
  src/test/http/walk.http
Labels: Feature

#33 산책 기간 조회 및 산책 목표 기능 추가
  src/main/java/com/concord/petmily/common/dto/ApiResponse.java
  src/main/java/com/concord/petmily/common/dto/Pagination.java
  src/main/java/com/concord/petmily/common/exception/ErrorCode.java
  src/main/java/com/concord/petmily/common/exception/ErrorResponse.java
  src/main/java/com/concord/petmily/domain/comment/dto/CommentDto.java
  src/main/java/com/concord/petmily/domain/comment/entity/Comment.java
  src/main/java/com/concord/petmily/domain/disease/dto/DiseaseDto.java
  src/main/java/com/concord/petmily/domain/disease/entity/Disease.java
  src/main/java/com/concord/petmily/domain/likes/entity/Likes.java
  src/main/java/com/concord/petmily/domain/pet/controller/PetController.java
  src/main/java/com/concord/petmily/domain/pet/dto/PetDto.java
  src/main/java/com/concord/petmily/domain/pet/entity/Pet.java
  src/main/java/com/concord/petmily/domain/pet/repository/PetRepository.java
  src/main/java/com/concord/petmily/domain/post/dto/PostDto.java
  src/main/java/com/concord/petmily/domain/post/entity/Hashtag.java
  src/main/java/com/concord/petmily/domain/post/entity/Post.java
  src/main/java/com/concord/petmily/domain/post/entity/PostCategory.java
  src/main/java/com/concord/petmily/domain/post/entity/PostHashtag.java
  src/main/java/com/concord/petmily/domain/post/entity/PostView.java
  src/main/java/com/concord/petmily/domain/user/controller/UserController.java
  src/main/java/com/concord/petmily/domain/user/entity/User.java
  src/main/java/com/concord/petmily/domain/vaccination/dto/VaccinationDto.java
  src/main/java/com/concord/petmily/domain/walk/controller/WalkController.java
  src/main/java/com/concord/petmily/domain/walk/dto/DailyWalkDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/DailyWalksDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/PetsWalkDetailDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkActivityDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkDetailDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkGoalDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkStatisticsDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkingPetDto.java
  src/main/java/com/concord/petmily/domain/walk/entity/Walk.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkActivity.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkGoal.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkParticipant.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkParticipantId.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkActivityRepository.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkGoalRepository.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkParticipantRepository.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkRepository.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkingPetRepository.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkGoalService.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkGoalServiceImpl.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkService.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkServiceImpl.java
  src/main/resources/data.sql
  src/test/http/user.http
  src/test/http/walk.http
  src/test/http/walkGoal.http
Labels: Feature

#35 관리자 권한, 알림기능, README.md 추가
  README.md
  src/main/java/com/concord/petmily/domain/auth/security/SecurityConfig.java
  src/main/java/com/concord/petmily/domain/comment/entity/Comment.java
  src/main/java/com/concord/petmily/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/concord/petmily/domain/likes/service/LikesServiceImpl.java
  src/main/java/com/concord/petmily/domain/notification/controller/NotificationController.java
  src/main/java/com/concord/petmily/domain/notification/dto/NotificationDto.java
  src/main/java/com/concord/petmily/domain/notification/entity/Notification.java
  src/main/java/com/concord/petmily/domain/notification/exception/NotificationException.java
  src/main/java/com/concord/petmily/domain/notification/repository/EmitterRepository.java
  src/main/java/com/concord/petmily/domain/notification/repository/NotificationRepository.java
  src/main/java/com/concord/petmily/domain/notification/service/NotificationService.java
  src/main/java/com/concord/petmily/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/concord/petmily/domain/post/controller/PostController.java
  src/main/java/com/concord/petmily/domain/post/service/PostService.java
  src/main/java/com/concord/petmily/domain/post/service/PostServiceImpl.java
  src/test/http/notification.http
  src/test/http/post.http
Labels: Feature

#34 오픈 채팅 기능 추가
  build.gradle
  src/main/java/com/concord/petmily/common/config/WebConfig.java
  src/main/java/com/concord/petmily/common/config/WebSocketConfig.java
  src/main/java/com/concord/petmily/common/dto/ApiResponse.java
  src/main/java/com/concord/petmily/common/dto/PagedApiResponse.java
  src/main/java/com/concord/petmily/domain/auth/security/SecurityConfig.java
  src/main/java/com/concord/petmily/domain/openchat/controller/ChatController.java
  src/main/java/com/concord/petmily/domain/openchat/controller/OpenChatController.java
  src/main/java/com/concord/petmily/domain/openchat/dto/ChatMessage.java
  src/main/java/com/concord/petmily/domain/openchat/dto/CreateChatRoomDto.java
  src/main/java/com/concord/petmily/domain/openchat/dto/JoinChatRoomDto.java
  src/main/java/com/concord/petmily/domain/openchat/dto/LeaveChatRoomDto.java
  src/main/java/com/concord/petmily/domain/openchat/dto/MessageDto.java
  src/main/java/com/concord/petmily/domain/openchat/dto/OpenChatDto.java
  src/main/java/com/concord/petmily/domain/openchat/dto/SendMessageDto.java
  src/main/java/com/concord/petmily/domain/openchat/dto/UpdateChatRoomDto.java
  src/main/java/com/concord/petmily/domain/openchat/entity/ChatStatus.java
  src/main/java/com/concord/petmily/domain/openchat/entity/OpenChat.java
  src/main/java/com/concord/petmily/domain/openchat/entity/OpenChatCategory.java
  src/main/java/com/concord/petmily/domain/openchat/entity/OpenChatMessage.java
  src/main/java/com/concord/petmily/domain/openchat/entity/OpenChatParticipant.java
  src/main/java/com/concord/petmily/domain/openchat/entity/OpenChatParticipantId.java
  src/main/java/com/concord/petmily/domain/openchat/entity/ParticipantStatus.java
  src/main/java/com/concord/petmily/domain/openchat/repository/OpenChatCategoryRepository.java
  src/main/java/com/concord/petmily/domain/openchat/repository/OpenChatParticipantRepository.java
  src/main/java/com/concord/petmily/domain/openchat/repository/OpenChatRepository.java
  src/main/java/com/concord/petmily/domain/openchat/service/MessageService.java
  src/main/java/com/concord/petmily/domain/openchat/service/MessageServiceImpl.java
  src/main/java/com/concord/petmily/domain/openchat/service/OpenChatService.java
  src/main/java/com/concord/petmily/domain/openchat/service/OpenChatServiceImpl.java
  src/main/java/com/concord/petmily/domain/post/controller/PostController.java
  src/main/java/com/concord/petmily/domain/post/service/PostServiceImpl.java
  src/main/java/com/concord/petmily/domain/user/entity/User.java
  src/main/java/com/concord/petmily/domain/walk/controller/WalkController.java
  src/main/java/com/concord/petmily/domain/walk/dto/EndWalkDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/StartWalkDto.java
  src/main/java/com/concord/petmily/domain/walk/dto/StartWalkRequest.java
  src/main/java/com/concord/petmily/domain/walk/dto/WalkDto.java
  src/main/java/com/concord/petmily/domain/walk/entity/Walk.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkService.java
  src/main/java/com/concord/petmily/domain/walk/service/WalkServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/static/html/index.html
  src/main/resources/static/html/login.html
  src/main/resources/static/html/open-chat-list.html
  src/main/resources/static/html/open-chat.html
  src/main/resources/static/html/walk.html
  src/main/resources/static/js/chat.js
  src/main/resources/templates/walk.html
  src/test/http/openchat.http
  src/test/http/walk.http
Labels: Feature

#38 산책 알림, 관리자 게시물 카테고리 수정 기능 추가
  src/main/java/com/concord/petmily/PetmilyApplication.java
  src/main/java/com/concord/petmily/domain/auth/security/SecurityConfig.java
  src/main/java/com/concord/petmily/domain/comment/controller/CommentController.java
  src/main/java/com/concord/petmily/domain/comment/service/CommentService.java
  src/main/java/com/concord/petmily/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/concord/petmily/domain/likes/controller/LikesController.java
  src/main/java/com/concord/petmily/domain/likes/repository/LikesRepository.java
  src/main/java/com/concord/petmily/domain/likes/service/LikesService.java
  src/main/java/com/concord/petmily/domain/likes/service/LikesServiceImpl.java
  src/main/java/com/concord/petmily/domain/notification/controller/NotificationController.java
  src/main/java/com/concord/petmily/domain/notification/dto/NotificationDto.java
  src/main/java/com/concord/petmily/domain/notification/entity/Notification.java
  src/main/java/com/concord/petmily/domain/notification/repository/NotificationRepository.java
  src/main/java/com/concord/petmily/domain/notification/service/NotificationService.java
  src/main/java/com/concord/petmily/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/concord/petmily/domain/pet/repository/PetRepository.java
  src/main/java/com/concord/petmily/domain/post/controller/PostController.java
  src/main/java/com/concord/petmily/domain/post/repository/HashtagRepository.java
  src/main/java/com/concord/petmily/domain/post/repository/PostHashtagRepository.java
  src/main/java/com/concord/petmily/domain/post/repository/PostRepository.java
  src/main/java/com/concord/petmily/domain/post/repository/PostViewRepository.java
  src/main/java/com/concord/petmily/domain/post/service/PostService.java
  src/main/java/com/concord/petmily/domain/post/service/PostServiceImpl.java
  src/main/java/com/concord/petmily/domain/user/controller/UserController.java
  src/main/java/com/concord/petmily/domain/user/entity/User.java
  src/main/java/com/concord/petmily/domain/user/repository/UserRepository.java
  src/main/java/com/concord/petmily/domain/user/service/UserDetailService.java
  src/main/java/com/concord/petmily/domain/user/service/UserService.java
  src/main/java/com/concord/petmily/domain/user/service/UserServiceImpl.java
  src/main/java/com/concord/petmily/domain/walk/repository/WalkGoalRepository.java
  src/test/http/notification.http
  src/test/http/post.http
  src/test/http/user.http
Labels: Feature

#42 회원 정보 수정 기능 추가
  src/main/java/com/concord/petmily/common/exception/ErrorCode.java
  src/main/java/com/concord/petmily/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/concord/petmily/domain/user/controller/UserController.java
  src/main/java/com/concord/petmily/domain/user/dto/AddAdminRequest.java
  src/main/java/com/concord/petmily/domain/user/service/UserService.java
  src/main/java/com/concord/petmily/domain/user/service/UserServiceImpl.java
  src/test/http/user.http
Labels: Feature

#43 코드 리팩토링 및 README 파일 작성
  README.md
  src/main/java/com/concord/petmily/common/exception/ErrorCode.java
  src/main/java/com/concord/petmily/common/utils/PasswordHashGenerator.java
  src/main/java/com/concord/petmily/domain/auth/service/TokenProvider.java
  src/main/java/com/concord/petmily/domain/chatmessage/controller/ChatMessageController.java
  src/main/java/com/concord/petmily/domain/pet/controller/PetController.java
  src/main/java/com/concord/petmily/domain/post/controller/PostController.java
  src/main/java/com/concord/petmily/domain/user/service/UserServiceImpl.java
  src/main/java/com/concord/petmily/domain/walk/controller/WalkController.java
  src/main/java/com/concord/petmily/domain/walk/dto/PetsWalkDetailDto.java
  src/main/java/com/concord/petmily/domain/walk/entity/WalkGoal.java
  src/main/resources/data.sql
  src/test/http/openchat.http
  src/test/http/post.http
  src/test/http/user.http
  src/test/http/vaccination.http
  src/test/http/walk.http
  src/test/http/walkGoal.http
Labels: documentation, Refactor
